[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[build.nix]
packages = ["cairo", "pango", "gdk-pixbuf"]

[deploy]
numReplicas = 1
startCommand = "sh start.sh"

[service]
port = 8080
