"""add_certificate_asset

Revision ID: fa3b90e003df
Revises: bddba790e4a8
Create Date: 2026-05-16 13:04:58.077102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa3b90e003df'
down_revision: Union[str, Sequence[str], None] = 'bddba790e4a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('file_binary', sa.LargeBinary(), nullable=False),
    sa.Column('file_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificates',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cert_type_id', sa.Integer(), nullable=False),
    sa.Column('template_version', sa.String(length=50), nullable=True),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('pdf_artifact', sa.LargeBinary(), nullable=True),
    sa.Column('pdf_hash', sa.String(length=128), nullable=True),
    sa.Column('sendgrid_message_id', sa.String(length=128), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cert_type_id'], ['certificate_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificate_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cert_id', sa.String(length=60), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('prev_hash', sa.String(length=128), nullable=False),
    sa.Column('entry_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('signature', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['cert_id'], ['certificates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_hash')
    )
    op.create_index(op.f('ix_certificate_ledger_cert_id'), 'certificate_ledger', ['cert_id'], unique=False)
    op.add_column('certificate_types', sa.Column('asset_id', sa.String(length=36), nullable=True))
    op.alter_column('certificate_types', 'master_pdf_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.create_foreign_key(None, 'certificate_types', 'certificate_assets', ['asset_id'], ['id'])
    op.add_column('job_queue', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.add_column('job_queue', sa.Column('checkpoint', sa.String(length=50), nullable=True))
    op.add_column('job_queue', sa.Column('locked_at', sa.DateTime(), nullable=True))
    op.add_column('job_queue', sa.Column('locked_by', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'job_queue', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_queue', type_='unique')
    op.drop_column('job_queue', 'locked_by')
    op.drop_column('job_queue', 'locked_at')
    op.drop_column('job_queue', 'checkpoint')
    op.drop_column('job_queue', 'idempotency_key')
    op.drop_constraint(None, 'certificate_types', type_='foreignkey')
    op.alter_column('certificate_types', 'master_pdf_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('certificate_types', 'asset_id')
    op.drop_index(op.f('ix_certificate_ledger_cert_id'), table_name='certificate_ledger')
    op.drop_table('certificate_ledger')
    op.drop_table('certificates')
    op.drop_table('certificate_assets')
    # ### end Alembic commands ###
